### PR TITLE
build exe

### PR DESCRIPTION
**Pull request by Mastermind-sap**

### CODE REVIEW

**Comment by Mastermind-sap** [comment]
what are these extra checks? and how to enable them?

**Comment by JDeepD** [comment]
Currently there is some problem with the exe version of open palm. I will modify it later.

**Comment by JDeepD** [comment]
> Currently there is some problem with the exe version of open palm. I will modify it later.

Due to a loophole.

**Comment by Mastermind-sap** [comment]
ok

**Pull request closed without merging**
